name: neon_task
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & state management
  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1
  google_fonts: ^6.3.3
  provider: ^6.1.5+1

  # Firebase (compatible versions)
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5

  # Notifications and timezone
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1

  # File & image handling
  image_picker: ^0.8.7+6
  file_picker: ^10.3.8

  # Audio and speech
  audioplayers: ^6.5.1
  speech_to_text: ^7.1.0

  # Local storage
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/
